common/fmt_common.h: include fmt/core.h
since fmt v11.1.0, formattable concept was moved into base.h, which
is in turn included by core.h. but in fmt v10.1.1, base.h didn't exist
at all. that's why the tree didn't compile with using libfmt v10.1.1:

```
/usr/bin/c++ -DBOOST_ASIO_DISABLE_THREAD_KEYWORD_EXTENSION -DBOOST_ASIO_NO_TS_EXECUTORS -DCEPH_INSTALL_DATADIR=\"/usr/local/share/ceph\" -DCEPH_INSTALL_FULL_PKGLIBDIR=\"/usr/local/lib/ceph\" -DCMAKE_INSTALL_LIBDIR=\"lib\" -DFMT_SHARED -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_REENTRANT -D_THREAD_SAFE -D__CEPH__ -D__STDC_FORMAT_MACROS -D__linux__ -I/home/kefu/dev/ceph/build/src/include -I/home/kefu/dev/ceph/src -I/home/kefu/dev/ceph/src/dmclock/support/src -isystem /home/kefu/dev/ceph/build/boost/include -isystem /home/kefu/dev/ceph/build/include -isystem /home/kefu/dev/ceph/src/jaegertracing/opentelemetry-cpp/api/include -isystem /home/kefu/dev/ceph/src/jaegertracing/opentelemetry-cpp/exporters/jaeger/include -isystem /home/kefu/dev/ceph/src/jaegertracing/opentelemetry-cpp/ext/include -isystem /home/kefu/dev/ceph/src/jaegertracing/opentelemetry-cpp/sdk/include -isystem /home/kefu/dev/ceph/src/xxHash -Og -g -std=c++23 -fPIC -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -Wall -fno-strict-aliasing -fsigned-char -Wtype-limits -Wignored-qualifiers -Wpointer-arith -Werror=format-security -Winit-self -Wno-unknown-pragmas -Wnon-virtual-dtor -Wno-ignored-qualifiers -ftemplate-depth-1024 -DBOOST_ALLOW_DEPRECATED_HEADERS -Wpessimizing-move -Wredundant-move -Wstrict-null-sentinel -Woverloaded-virtual -DCEPH_DEBUG_MUTEX -fstack-protector-strong -D_GLIBCXX_ASSERTIONS -fdiagnostics-color=auto -MD -MT src/common/CMakeFiles/common-common-objs.dir/Formatter.cc.o -MF src/common/CMakeFiles/common-common-objs.dir/Formatter.cc.o.d -o src/common/CMakeFiles/common-common-objs.dir/Formatter.cc.o -c /home/kefu/dev/ceph/src/common/Formatter.cc
In file included from /home/kefu/dev/ceph/src/common/Formatter.h:16,
                 from /home/kefu/dev/ceph/src/common/Formatter.cc:18:
/home/kefu/dev/ceph/src/common/fmt_common.h:6:10: fatal error: fmt/base.h: No such file or directory
    6 | #include <fmt/base.h>
      |          ^~~~~~~~~~~~
```

since our minimal supported version of fmt library is 8.1.1, we
need to support libfmt 10.1.1. in this change, we replace
fmt/base.h with fmt/core.h, and move this `#include` closer to other
`#include <fmt/*>`.

Signed-off-by: Kefu Chai <k.chai@proxmox.com>