qa/tasks: fix import error
```
2026-02-04 06:04:16,385.385 INFO:__main__:    from .helper import DashboardTestCase, MgrModuleTestCase
2026-02-04 06:04:16,385.385 INFO:__main__:ImportError: cannot import name 'MgrModuleTestCase' from 'tasks.mgr.dashboard.helper' (/home/jenkins-build/build/workspace/ceph-api/qa/tasks/mgr/dashboard/helper.py)
```

Signed-off-by: Nizamudeen A <nia@redhat.com>
(cherry picked from commit 99e46d2cf05ed16e9f26bee191d2e789bfc10970)